title: Wedde
logo: /demo/blur_portrait.png
description: Add effects to a webcam in Linux for Zoom, Webex, or other calls, or stream a video to a webcam, including blurred background
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
